frontend.validSearchAttributes:
- value:
    DomainID: 1
  constraints: {}
testGetBoolPropertyKey:
- value: false
  constraints: {}
- value: true
  constraints:
    domainName: global-samples-domain
- value: true
  constraints:
    domainName: samples-domain
testGetDurationPropertyKey:
- value: 1m
  constraints: {}
- value: wrong duration string
  constraints:
    domainName: samples-domain
    taskListName: longIdleTimeTasklist
- value: 2
  constraints:
    domainName: samples-domain
testGetFloat64PropertyKey:
- value: 12
  constraints: {}
- value: wrong type
  constraints:
    domainName: samples-domain
testGetIntPropertyKey:
- value: 1000
  constraints: {}
- value: 1000.1
  constraints:
    domainName: global-samples-domain
testGetMapPropertyKey:
- value:
    key1: "1"
    key2: 1
    key3:
    - false
    - key4: true
      key5: 2.1
  constraints: {}
- value: "1"
  constraints:
    taskListName: random tasklist
testGetStringPropertyKey:
- value: some random string
  constraints: {}
- value: constrained-string
  constraints:
    taskListName: random tasklist
