persistence:
  defaultStore: cass-default
  visibilityStore: cass-visibility
  numHistoryShards: 4
  datastores:
    cass-default:
      cassandra:
        hosts: "127.0.0.1"
        keyspace: "cadence_standby"
        consistency: "One"
    cass-visibility:
      cassandra:
        hosts: "127.0.0.1"
        keyspace: "cadence_visibility_standby"
        consistency: "One"

ringpop:
  name: cadence_standby
  bootstrapMode: hosts
  bootstrapHosts: ["127.0.0.1:8933", "127.0.0.1:8934", "127.0.0.1:8935", "127.0.0.1:8940"]
  maxJoinDuration: 30s

services:
  frontend:
    rpc:
      port: 8933
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence_standby"
    pprof:
      port: 8936

  matching:
    rpc:
      port: 8935
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence_standby"
    pprof:
      port: 8938

  history:
    rpc:
      port: 8934
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence_standby"
    pprof:
      port: 8937

  worker:
    rpc:
      port: 8940
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence_standby"
    pprof:
      port: 8941

clusterMetadata:
  enableGlobalDomain: true
  replicationConsumer:
    type: rpc
    fetcher:
      rpcParallelism: 1
      aggregationIntervalSecs: 2
      errorRetryWaitSecs: 1
      timerJitterCoefficient: 0.15
    processor:
      noTaskInitialWaitIntervalSecs: 2
      noTaskWaitBackoffCoefficient: 1
      noTaskMaxWaitIntervalSecs: 2
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "standby"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 1
      rpcName: "cadence-frontend"
      rpcAddress: "localhost:7933"
    standby:
      enabled: true
      initialFailoverVersion: 0
      rpcName: "cadence-frontend"
      rpcAddress: "localhost:8933"

dcRedirectionPolicy:
  policy: "selected-apis-forwarding"
  toDC: ""

kafka:
  tls:
    enabled: false
    certFile: ""
    keyFile: ""
    bundleFile: ""
  clusters:
    test:
      brokers:
        - 127.0.0.1:9092
  topics:
    active:
      cluster: test
    active-dlq:
      cluster: test
    standby:
      cluster: test
    standby-dlq:
      cluster: test
  cadence-cluster-topics:
    active:
      topic: active
      dlq-topic: active-dlq
    standby:
      topic: standby
      dlq-topic: standby-dlq

archival:
  history:
    status: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"
  visibility:
    status: "disabled"
    enableRead: false

domainDefaults:
  archival:
    history:
      status: "enabled"
      URI: "file:///tmp/cadence_archival/development"
    visibility:
      status: "disabled"

publicClient:
  hostPort: "localhost:8933"

